# Generated by Django 4.2.23 on 2025-09-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Library ID in format lib:ORG:SLUG", max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("org", models.CharField(help_text="Organization name", max_length=255)),
                ("slug", models.CharField(help_text="Library slug/identifier", max_length=255)),
                ("title", models.CharField(help_text="Library title", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Library description")),
            ],
            options={
                "verbose_name": "Library",
                "verbose_name_plural": "Libraries",
                "ordering": ["title"],
            },
        ),
    ]
