# Generated by Django 5.2.7 on 2025-10-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_authz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlibraryscope',
            name='scope_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openedx_authz.scope'),
        ),
    ]
