# Generated by Django 4.2.24 on 2026-02-06 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stubs", "__first__"),
        ("openedx_authz", "0006_migrate_legacy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseScope",
            fields=[
                (
                    "scope_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="openedx_authz.scope",
                    ),
                ),
                (
                    "course_overview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authz_scopes",
                        to=settings.OPENEDX_AUTHZ_COURSE_OVERVIEW_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("openedx_authz.scope",),
        ),
    ]
