# Generated by Django 4.2.24 on 2026-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_authz", "0007_coursescope"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignmentAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("created", "created"), ("deleted", "deleted")],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Namespaced key of the subject (e.g. 'user^john_doe').",
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Namespaced key of the role (e.g. 'role^library_admin').",
                        max_length=255,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        help_text="Namespaced key of the scope (e.g. 'course-v1^course-v1:org+course+run') or glob pattern.",
                        max_length=255,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        blank=True,
                        help_text="Username of the user who performed the operation, or None for system-initiated actions.",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Role Assignment Audit",
                "verbose_name_plural": "Role Assignment Audits",
                "ordering": ["-timestamp"],
            },
        ),
    ]
