# Generated by Django 5.2.12 on 2026-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openedx_authz", "0007_coursescope"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthzCourseAuthoringMigrationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "migration_type",
                    models.CharField(
                        choices=[("forward", "Legacy to AuthZ"), ("rollback", "AuthZ to Legacy")],
                        help_text="Direction of migration: forward (legacy → authz) or rollback (authz → legacy)",
                        max_length=20,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("course", "Course"), ("org", "Organization")],
                        help_text="Type of scope being migrated: course or organization",
                        max_length=20,
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        help_text="Identifier for the scope (e.g., course-v1:edX+DemoX+DemoCourse or org name)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial_success", "Partial Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        help_text="Current status of the migration run",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the migration run was created")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When the migration run was last updated"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When the migration run was completed", null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the migration run (e.g., counts, warnings, errors)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Authoring Migration Run",
                "verbose_name_plural": "Course Authoring Migration Runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["scope_type", "scope_key"], name="openedx_aut_scope_t_d43a35_idx"),
                    models.Index(fields=["status"], name="openedx_aut_status_e34b60_idx"),
                    models.Index(fields=["-created_at"], name="openedx_aut_created_ab3e0a_idx"),
                ],
            },
        ),
    ]
