# Generated by Django 4.2.24 on 2026-02-17 22:31

import logging

from django.db import migrations

from openedx_authz.engine.utils import migrate_legacy_course_roles_to_authz

logger = logging.getLogger(__name__)


def _log_migration_errors(permissions_with_errors: list) -> None:
    """
    Log the permissions that could not be migrated during the migration process.
    Args:
        permissions_with_errors (list): List of CourseAccessRole instances that failed to migrate.
    """
    logger.error(
        f"Migration completed with errors for {len(permissions_with_errors)} permissions.\n"
        "The following permissions could not be migrated:"
    )
    for permission in permissions_with_errors:
        logger.error(
            "Role: %s, %sCourse: %s",
            permission.role,
            f"User: {permission.user.username}, " if permission.user else "",
            permission.course_id,
        )


def apply_migrate_legacy_course_roles_to_authz(apps, schema_editor):
    """
    Wrapper to run the migration using the historical version of the CourseAccessRole model.
    """
    # CourseAccessRole model from the student app, here is where the legacy course roles are stored
    try:
        CourseAccessRole = apps.get_model("student", "CourseAccessRole")
    except LookupError:
        # Don't run the migration where the student app is not installed, like during development.
        logger.warning("CourseAccessRole model not found. Skipping migration.")
        return

    permissions_with_errors = migrate_legacy_course_roles_to_authz(CourseAccessRole, delete_after_migration=True)

    if permissions_with_errors:
        _log_migration_errors(permissions_with_errors)


class Migration(migrations.Migration):
    dependencies = [
        ("openedx_authz", "0007_coursescope"),
    ]

    operations = [
        migrations.RunPython(apply_migrate_legacy_course_roles_to_authz),
    ]
