# Generated by Django 4.2.24 on 2026-04-14 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openedx_authz", "0007_coursescope"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignmentAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("created", "created"), ("deleted", "deleted")],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("scope", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_role_assignment_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Assignment Audit",
                "verbose_name_plural": "Role Assignment Audits",
                "ordering": ["-timestamp"],
            },
        ),
    ]
