# Generated by Django 5.2.16 on 2026-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_authz', '0009_roleassignmentaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='external_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
